### ISSUE TITLE
[Bug]:  Changes are not reflecting. 

### ISSUE THREAD

**Issue by ArunNathan** [Status-Page/Status-Page#540]
### Description of the Bug

We are trying to remove the Management URL: and Subscriber URL: from the email templates. 

We have removed in Created.html and Created.txt file in the incidents folder. 

But still we are getting the links in emails. 

### Expected behavior

Management URL: status-page.fullaw.in/subscribers/54285679-e187-4dd0-b10b-433a9d75783b/manage
Unsubscribe URL: status-page.fullaw.in/subscribers/54285679-e187-4dd0-b10b-433a9d75783b/unsubscribe

I want to remove this from the email templates. 

### Version

> 2.0.0 (Preview)

### Information about your Device

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by HerrTxbias** [comment]
If you removed all URLs (both in incidents and maintenances), they should no longer show up in emails. You may need to restart the workers so that they reload the templates. To simplify the customization of the email templates, I will develop a feature so that you can use your own templates or customize the existing ones.

However, I strongly recommend **_not removing_** at least the unsubscribe link, as this is a **legal requirement in many countries** around the world. This is not legal advice though, as I am not a lawyer.

**Comment by ArunNathan** [comment]
Hi, We have removed in both incidents and maintenances templates. Still receiving with the Management URL. 

Can someone help us.

**Comment by HerrTxbias** [comment]
In which emails do you still receive them? It is not possible that you still receive them, if you have removed them from the template.
